### ISSUE TITLE
Show date and time in proper format

### ISSUE THREAD

**Issue by schulz-alexander** [xcp-ng/xenadmin#163]
Show date and time like set in the regional settings.

In non-american countrys it shows the time in AM/PM format and the date in "american" format :-/ Not the most fun for non-american people.

**Comment by schulz-alexander** [comment]
Before:
![grafik](https://user-images.githubusercontent.com/5782951/58373675-2bb6bf80-7f32-11e9-92e1-585ec037cf31.png)



So it makes more sense to me:
![grafik](https://user-images.githubusercontent.com/5782951/58373658-cebb0980-7f31-11e9-98b7-cd116b682d4c.png)

Of course the localised date and time format might not fit into all UI elements, but this is more attractive to me then interpreting the time from AM/PM and delete the wrong snapshot because of that.

Just for reference, it's somehow related to CITRIX internal bug tracker CA-46983 on which we don't have access to.

**Comment by cocoon** [comment]
For me exactly these times are much easier ^^

Just one thing, is it converting only the Culture or also converting to local timezone?
Because maybe if one manages a remote host that runs in another country, maybe one wants to see what is the remote (server local) time ... tooltip? Option?

But how to read servers timezone ... without a plugin it will be difficult I think.
... oh no just found Host.getServerTime ... tried it, could be working ... but I found an old bug report:

https://discussions.citrix.com/topic/265895-hostgetservertime-gives-the-date-in-incorrect-time-zone/

And indeed, I tried it in my plugin and the times are different:

Host.getServerTime:
![grafik](https://user-images.githubusercontent.com/1071741/58374254-91f41000-7f3b-11e9-991f-6e38f4222a2a.png)

ssh date reports:
Sat May 25 05:10:33 CEST 2019

**Comment by cocoon** [comment]
OK it is possible to get the current servers time, but no timezone information as far as I can see:

XenAPI.Host.get_servertime(session, host);
--> ServerTime: 25.05.2019 07:10:39

XenAPI.Host.get_server_localtime(session, host);
--> Serer LocalTime: 25.05.2019 09:10:39

Was just an idea if it would have been easy to get, but yes, seeing the local time in the graph and list is great :)

**Comment by Daksol** [comment]
Suggest you go with ISO 8601 dates as the default which provide a universal option. They will confuse neither Americans nor Europeans, and probably not Martians either.

XKCD says: https://xkcd.com/1179/

Good wiki entry https://en.wikipedia.org/wiki/ISO_8601

Time date stamp like 2016-11-27T14:45:32Z
for 27 Nov 2016, at 14:45 UTC time (the Z denotes UTC time).

**Comment by schulz-alexander** [comment]
we will not work on that
