### ISSUE TITLE
Show Version in Title

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#17]
Would this be helpfull?

**Comment by cocoon** [comment]
Maybe not in the title, one thing I could think of are automated scripts that target a window by title like here: https://www.autoitscript.com/autoit3/docs/functions/WinGetHandle.htm

But the AssemblyFileVersion might be a good place to be filled so that if you right click one of the files and select the properties go to the details tab that you can see a version instead of 0.0.0.0:
https://github.com/xcp-ng/xenadmin/blob/release-7.4.0.2/XenAdmin/Properties/AssemblyInfo.cs#L64

**Comment by borzel** [comment]
Seems not to be needed -> close
