### ISSUE TITLE
Publish to chocolatey.org library

### ISSUE THREAD

**Issue by cfoellmann** [xcp-ng/xenadmin#189]
There is already a .msi package so the xenadmin/xcp-ng center should be available via chocolatey.
This way it can be kept up-to-date easily.

**Comment by AntonOks** [comment]
> 
> 
> There is already a .msi package so the xenadmin/xcp-ng center should be available via chocolatey.
> This way it can be kept up-to-date easily.

if you would be willing to use [scoop ](https://scoop.sh/) instead of chocolatey, you could add my scoop bucket and install the "latest" release...

1. install scoop (see guide in https://scoop.sh/)
2. add my bucket via `scoop bucket add scoop-aoks https://github.com/AntonOks/scoop-aoks.git`
3. install via `scoop install xcp_ng-center-aoks`
4. keep everything up2date via `scoop update *`

I'll later try to get this into the official standard ["scoop extras"](https://github.com/lukesampson/scoop-extras) bucket. Need first to see if the coming Center release naming stays as I think it is meant to be...

enjoy...

**Comment by schulz-alexander** [comment]
we will not work on that
