### ISSUE TITLE
Connecting xenadmin to Alpine XEN

### ISSUE THREAD

**Issue by Outstep** [xcp-ng/xenadmin#201]
Hi All,

Not sure if this is the correct place to ask this, but I have been playing with the Alpine-XEN Live distro and have installed it to a USB.

Since it is running in RAM, I would like to be able to connect to it with the xenadmin.

I "might" have to install XAPI or some other packages but am not sure how to proceed.

With that in mind, I wondering if anyone has done this yet?
Any help or guidance would be greatly appreciated.
Cheers

**Comment by olivierlambert** [comment]
Citrix Hypervisor and XCP-ng are the only XAPI-capable distros. One can't just install XAPI on another distro, because it wasn't built to be easily deployed outside the very specific environment that the 2 previous distro I listed before.

On Alpine, you have lib xl that can be compatible with libvirt if I remember correctly.

**Comment by olivierlambert** [comment]
See https://xcp-ng.org/docs/architecture.html#api for more details.

**Comment by schulz-alexander** [comment]
As @olivierlambert wrote, xapi will not work on Alpine XEN.

I you or someone else can make xapi work on Alpine XEN, make a new ticket here an we will try to make it work.
