### ISSUE TITLE
Minor gui issue: Allow Line Endings in Xen Center

### ISSUE THREAD

**Issue by justingoldberg** [xcp-ng/xenadmin#204]
Allow Cr/Lf in the description of the guest in xen center. I know that XCP center isn't a documentation repository, but still it would be nice.

![2021-05-27 09_54_53-'XOA redo from sources' Properties](https://user-images.githubusercontent.com/6743293/119839270-0c145200-bed2-11eb-9454-88c8f2240f13.png)

**Comment by cocoon** [comment]
This should already support multiline, you just have to paste the text into the Textbox there.
Enter is not working inside because it directly sends the OK for the form.

If that is what you request, it would be better to ask over at xenadmin (after trying with C. Hypervisor first if it still behaves the same, as far as I can see at least XenCenter-8.2.3 still behaves like this):

https://github.com/xenserver/xenadmin

**Comment by schulz-alexander** [comment]
**How it works and looks in XCP-ng Center:**

![grafik](https://github.com/xcp-ng/xenadmin/assets/5782951/42722803-efeb-4665-8a39-93dca0312b32)

![grafik](https://github.com/xcp-ng/xenadmin/assets/5782951/dc358ef5-d8c0-491f-811f-2ba47a9c7861)

**and Xen Orchestra:**

![grafik](https://github.com/xcp-ng/xenadmin/assets/5782951/69485a3f-7a5d-4738-a95f-0efb934526e1)
