### ISSUE TITLE
More future-proof installer/updater?

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#35]
thanks to @gangsterrapper22 we have an installer for XCP-ng Center 7.4.1!

But what want we to do in future?
* integrate installer sources to our repo?
* stick to a simple installer?
* autoupdate of XCP-ng Center?
* msi-based or someting NSIS-based?

Please share your experience/opinions

**Comment by olivierlambert** [comment]
IMHO, closer to the upstream the better (so MSI, etc.)

**Comment by skajter** [comment]
Agree with @olivierlambert - MSI is closer to 'base'.
As for part of auto-update, I'm not sure that we must do anything fancy right now, what I'm thinking is make stable release that will be linked in wit all basic features (ISO, XCP-ng, scripts, etc), then if we have request to add extra features, we will more likely talk with Citrix, to align our source code with them, to fetch updates form them (to avoid reinvent wheel).

Including installer scripts/files in github, is always good idea :) - only exception for MSI is, that if is signed, then private key must be hidden ;p

**Comment by gangsterrapper22** [comment]
MSI would be the best in tis case because it can easier deployed than other setups. Maybe we should also think to include the Installer Files, that it can be also built, when someone clones this Repo. For the Update, we can maybe include one version in the ISO and one maybe on an Webserver where the latest version can be downloaded.

**Comment by borzel** [comment]
just put it in a feature branch, so we can optimize it

**Comment by gangsterrapper22** [comment]
I have created an new feature branch with the Name XCP-ng_Center_Installer_Source but somehow it doesn't included my Installer Source. I will have a look tomorrow on it.

**Comment by gangsterrapper22** [comment]
Sorry for the delay with Uploading the Sources Files of my Installer. I still didn't get it, that it does also upload my Files. It only creates the Folder, but it doesn't add the files within. Maybe I have to delete and create the Feature Branch again.

**Comment by borzel** [comment]
Go to folder and do "git add *" or similiar. Which software are you using?

**Comment by gangsterrapper22** [comment]
I have now add the Installer Files in the Feature Branch XCP-ng_Center_Installer_Source. The Files are in the Folder XCP-ng_Center_Installer but some path are reffering to my local environment which has to adjust then.

**Comment by borzel** [comment]
I did integrate the installer sources from @gangsterrapper22 into XenAdmin.sln and into our branding-script. This should allow us to later create the msi with a buildserver :-)

Here is the branded end-product (for testing purposes only):
[installer-xcp-ng.zip](https://github.com/xcp-ng/xenadmin/files/2041926/installer-xcp-ng.zip)

**Comment by gangsterrapper22** [comment]
I just tried the Installer and it looks like that there are some bugs in it. The Shortcut on the Desktop points to "C:\Program Files (x86)\XCP-ng Center\~~XenCenter~~.exe" and I also get errors for missing DLL's like VCRUNTIME140D.dll, ucrtbased.dll, and MSVCP140D.dll. Did you change something on the sources? The DLL's with an D at the end looks like that you has compiled it in Debug Mode instead of Release Mode? Is this the case or not?

**Comment by borzel** [comment]
Shortcut is fixed: [installer-xcp-ng.zip](https://github.com/xcp-ng/xenadmin/files/2042746/installer-xcp-ng.zip)

**Comment by borzel** [comment]
Now you can get different versions of the msi, version 7.5 and "master" (https://builds.schulzalex.de/xcp-ng).

I installed XCP-ng Center 7.5 and upgraded using the "master" msi (it has version 99.99.99) without problems.

Can please someone else verify this?
