### ISSUE TITLE
Settings are not read on mono

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#43]
Actual the settings are saved to *.exe.config, but can not be read back in mono.

**Comment by cocoon** [comment]
This is a hard one! Was fighting a lot with it.
And I still don't understand it.

The problem is, that it is writing the config to:
```
/home/user/.config/XCP-ng/XenCenterMain.exe_Url_8b6f2abbddff56d898000b97c20ac0664cb383cb/user.config
```

and rading the config from:
```
/home/user/.local/share/XCP-ng/XenCenterMain.exe_Url_8b6f2abbddff56d898000b97c20ac0664cb383cb/user.config
```

And one more funny path that is checked and returned if you run:

**Settings.GetUserConfigPath():** 
```
/home/user/.config/XCP-ng Console_evidencehere/1.0.0.0/user.config
```

**ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None).FilePath: (this one is OK)** 
```
/home/user/Schreibtisch/dev/xenadmin/XenAdmin/bin/Debug/XenCenterMain.exe.config
```

**ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoamingAndLocal).FilePath:** 
```
/home/user/.local/share/XCP-ng Console_evidencehere/1.0.0.0/user.config
```

**Comment by borzel** [comment]
Ubuntu 18.04
Mono 5.12 (since today)
MonoDevelop Version 7.5 Preview (7.5 build 1245)

**Comment by borzel** [comment]
I build an settings abstraction layer prototype. Settings are saved to "/tmp/center.settings" (for testing purposes only)

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
