### ISSUE TITLE
.Net/Mono abstraction layers OR .Net/Mono builds

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#53]
Test, if we can build one version with .net and mono support
OR
if we have to ship separate .net and ono versions

**Comment by Storycrafter** [comment]
I'll take a look at this and see what I can do. This is my most important need right now -- Linux desktop support for this tool.

**Comment by olivierlambert** [comment]
Hi @Storycrafter 

I'd like to know why, in the light of this:

1. there's not enough maintainers on this project, and it caused problems (applying Citrix updates on XCP-ng etc.)
2. there's plan to make a new UI for Xen Orchestra (with a tree view, as requested by a part of the community). XO can be used on any modern browser, regardless the OS
3. there's also plans for XO Lite, a web UI that will run directly on the host (defeating the last argument for XCP-ng Center, ie not having to deploy an XO VM to manage a very small infrastructure)

**Comment by Storycrafter** [comment]
@olivierlambert Are you suggesting you don't want further help on this project?

**Comment by olivierlambert** [comment]
I'm not suggesting anything. Feel free to do what you want with it :smile: Just giving you the context.

* Facts: one community maintainer, it triggered some problems in a recent past, we can't keep up with Citrix decisions on upstream because they are 3 full time on it.
* My opinion: we should try to focus our efforts on more "modern" tools where we are less Citrix-dependent. But I'm trying to grasp why people want to port a heavy Windows client to another system, it's a bit a mystery to me. I mean, knowing that you have XO.

The last identified reasons for people to not use XO (which is backed by 6 devs full time):
* having a more classical tree view
* don't want to deploy a VM just to manage my host

Both of them will be fixed this year, so if you have another use case, let me know so we can provide "better tools" for everyone :+1:

**Comment by Storycrafter** [comment]
I get your motivations.  Unfortunately, as a hobbyist, I have somewhat different motivations. Having XO available is _almost_ a substitute. I really need the features in the paid version (particularly the updating and backup features), and I have struggled recently trying to re-orient myself to XO's UX. That it is a VM doesn't bother me at all -- the install from XCP-ng's browser (and the XO site) is simply amazing and really surprised me with how seamless that was.

Not being able to figure out how to put the 2 servers I just installed XCP-ng onto into a common pool after clicking around in XO for 20 minutes made me realize I could do that task in 20 seconds with xenadmin. That's why I thought maybe I might invest time porting it to Linux so I could run it on my main desktop instead of an old Windows VM.

I took a look at the source project last night. It's not a trivial task anyway. Everything has to get ported to .NetCore 3, and as you mentioned -- we're downstream and this would be a big boulder to roll back up the changelog hill.

**Comment by olivierlambert** [comment]
Wait, why not using XO from the sources? https://xen-orchestra.com/docs/installation.html#from-the-sources You have all XO features for free. So problem solved on that side.

Regarding the UI, I already said it will be fixed with the next XO UI, being closer at some point to the "tree view". Obviously, your feedback on what caused your issue with XO current UI is always helpful to improve next XO UI :) (and XOLite too)

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
