### ISSUE TITLE
Rolling Pool Upgrade not working properly

### ISSUE THREAD

**Issue by emersonkfuri** [xcp-ng/xenadmin#93]
**Describe the bug**
Rolling Pool upgrade interface is unable to apply hotfix needed to upgrade Xen installations. Not working with Citrix XenServer neither XCP-NG.

**Hard-/Software involved:**
 - Host XCP-ng Version: 7.4.1
 - Host XCP-ng Version: 7.4.0
 - Host Citrix XenServer: 7.2.0
 - Client XCP-ng Center Version: 7.5.0

**Comment by olivierlambert** [comment]
Hi!

What I can tell, regarding XCP-ng: patches mechanism is completely different. So it's normal that it doesn't work. However, you can update easily from XO: https://xen-orchestra.com/blog/xcp-ng-updates-from-xen-orchestra/

Note: personally, I don't like the automated rolling upgrade because it's unnecessarily complicated. The XenCenter code behind is completely spaghetti-like, and in the end, it's far less secure than moving around your VM and reboot only when needed (from my experience). Also, `yum` update system in XCP-ng also demonstrate that you can update without a lot of pain.

Regarding XenServer+XCP-ng Center, I can't answer myself.

**Comment by emersonkfuri** [comment]
Hello,

Unfortunately, we don't have an XOA subscription. I tried to upgrade XCP-ng 7.4.1 to XCP-ng 7.5 via yum and except by the loss of IQN, everything was fine.

Thank you,

**Comment by olivierlambert** [comment]
You don't need a XOA subscription, you can alternatively [install it from the sources](https://xen-orchestra.com/docs/from_the_sources.html) if it's not for production use (you won't have support but it's free) ;)

**Comment by emersonkfuri** [comment]
Mmm... Very strange! XOA's patch screen is requiring at least Standard Edition...

**Comment by olivierlambert** [comment]
* XOA: Xen Orchestra **Appliance**. This is the turnkey solution that require a subscription to get features an support
* Xen Orchestra from the sources: you install it yourself (cf the link I posted)

**Comment by emersonkfuri** [comment]
Thanks!

**Comment by borzel** [comment]
We have to remove such points to reflect more the main use of XCP-ng Center. It's the same for licenseing stuff.

**Comment by borzel** [comment]
I decided to remove the following menu entries:
* Rolling Pool Upgrade
* License Manager
